Reactivated documentation
vtexdocs/dev-portal-content pull request #1019
Opened 2024-03-04 22:48 UTC by geisecosta

#### Types of changes
- [x] New content (guides, endpoints, app documentation)
- [ ] Improvement (make a documentation even better)
- [ ] Fix (fix a documentation error)
- [ ] Spelling and grammar accuracy (self-explanatory)

2024-03-06 17:29 UTC, julia-rabello requested changes

2024-03-06 17:29 UTC, julia-rabello commented on docs/vtex-io/Storefront-Guides/b2b-setup.md
Faltou adicionar o conteúdo (só tem o frontmatter no arquivo).

2024-03-06 17:29 UTC, julia-rabello commented on docs/vtex-io/Storefront-Guides/b2b-setup/querying-b2b-order-statuses.md
> +> ⚠️The Querying B2B order statuses app has been deprecated in favor of the [B2B Orders History](https://developers.vtex.com/docs/apps/vtex.b2b-orders-history) app. Although this app has limited supp
Em "Although this app has limited support", não ficou claro qual app tem limited support. B2B Order status ou B2B Orders History?

2024-03-06 17:29 UTC, julia-rabello commented on docs/vtex-io/Storefront-Guides/b2b-setup/querying-b2b-order-statuses.md
> +> ⚠️The Querying B2B order statuses app has been deprecated in favor of the [B2B Orders History](https://developers.vtex.com/docs/apps/vtex.b2b-orders-history) app. Although this app has limited supp
```suggestion
> ⚠️This guide uses the B2B Orders app, which has been deprecated in favor of the [B2B Orders History](https://developers.vtex.com/docs/apps/vtex.b2b-orders-history) app. Although this app has limited support, we strongly recommend you update your store theme with the [B2B Suite](https://developers.vtex.com/docs/apps/vtex.b2b-suite) app to keep up with the component's evolution.
```

2024-03-06 17:29 UTC, julia-rabello commented on docs/vtex-io/Storefront-Guides/b2b-setup/querying-b2b-order-statuses.md
> +In a B2B business model, your company and your partners may need to share selected information, such as order statuses. This is necessary when you want to show the status of external orders — orders
```suggestion
In a B2B business model, your company and your partners may need to share selected information, such as order statuses. This is necessary to show the status of external orders — orders made outside VTEX — to customers on your ecommerce, for example.
```

2024-03-06 17:29 UTC, julia-rabello commented on docs/vtex-io/Storefront-Guides/b2b-setup/querying-b2b-order-statuses.md
> +> ⚠️ The B2B Orders app is not compatible with the [B2B Suite](https://developers.vtex.com/docs/guides/vtex-b2b-suite) solution. Therefore, these instructions do not apply to stores using the B2B Sui
Isso aqui deveria aparecer mais para cima. Talvez até mesclar com o conteúdo do primeiro callout.

2024-03-18 22:58 UTC, geisecosta commented on docs/vtex-io/Storefront-Guides/b2b-setup.md
Este arquivo possui informações dentro de um card <Flex>. Que tipo de informação estaria faltando?

2024-03-25 19:29 UTC, julia-rabello approved these changes

2024-03-25 20:18 UTC, merged