Update multiple-page-template.mdx
vtexdocs/dev-portal-content pull request #1049
Opened 2024-03-26 14:39 UTC by Mariana-Caetano

#### Types of changes
- [ ] New content (guides, endpoints, app documentation)
- [ ] Improvement (make a documentation even better)
- [x] Fix (fix a documentation error)
- [ ] Spelling and grammar accuracy (self-explanatory)

2024-03-26 21:08 UTC, carolinamenezes requested changes

2024-03-26 21:08 UTC, carolinamenezes commented on docs/faststore/docs/headless-cms/multiple-page-template.mdx
> +```
Faltou um passo antes? Achei que esse comando ficou solto

2024-03-26 21:08 UTC, carolinamenezes commented on docs/faststore/docs/headless-cms/multiple-page-template.mdx
> +After the sync, you can start [using the templates](#usage).
Não achei esse header de usage 👀

2024-04-25 13:54 UTC, carolinamenezes requested changes

2024-04-25 14:21 UTC, Mariana-Caetano commented on docs/faststore/docs/headless-cms/multiple-page-template.mdx
> +2. Update the `@faststore/cli` package to the latest version, `v.2.0.24`:
3!

2024-04-25 14:22 UTC, carolinamenezes approved these changes

2024-04-25 14:26 UTC, merged