Create cart-attachments-section-api-quick-start-guides.md
vtexdocs/dev-portal-content pull request #106
Opened 2023-01-10 00:46 UTC by ricardoaerobr

#### Types of changes
- [X] New content (guides, endpoints, app documentation)
- [ ] Improvement (make a documentation even better)
- [ ] Fix (fix a documentation error)
- [ ] Spelling and grammar accuracy (self-explanatory)

New .md created to list all Cart Attachments API Quick Start Guides.

2023-01-10 16:12 UTC, karenkrieger requested changes

2023-01-10 16:12 UTC, karenkrieger commented on docs/guides/Checkout/cart-attachments-section-api-quick-start-guides.md
> +This section contains the quick start guides of the endpoints described in the [Cart Attachments section](https://developers.vtex.com/docs/api-reference/checkout-api-overview#cart-attachments) of the
O link tá dando 404

2023-01-10 19:06 UTC, ricardoaerobr commented on docs/guides/Checkout/cart-attachments-section-api-quick-start-guides.md
> +This section contains the quick start guides of the endpoints described in the [Cart Attachments section](https://developers.vtex.com/docs/api-reference/checkout-api-overview#cart-attachments) of the
Link atualizado para o novo arquivo. Deverá estar disponível após o builder.

2023-01-11 13:46 UTC, ricardoaerobr commented on docs/guides/Checkout/cart-attachments-section-api-quick-start-guides.md
> +This section contains the quick start guides of the endpoints described in the [Cart Attachments section](https://developers.vtex.com/docs/api-reference/checkout-api-overview#cart-attachments) of the
Link atualizado e já publicado: https://developers.vtex.com/docs/guides/checkout-api-overview#cart-attachments

2023-01-12 15:34 UTC, karenkrieger approved these changes
LGTM

2023-01-12 15:39 UTC, merged