add queries
vtexdocs/dev-portal-content pull request #1063
Opened 2024-04-01 19:31 UTC by Mariana-Caetano

#### Types of changes
- [ ] New content (guides, endpoints, app documentation)
- [ ] Improvement (make a documentation even better)
- [ ] Fix (fix a documentation error)
- [ ] Spelling and grammar accuracy (self-explanatory)

2024-04-25 13:50 UTC, carolinamenezes requested changes
Página de preview: https://developers.vtex.com/docs/guides/faststore/schema-queries

- Arrumar os haslinks para a página em que vai estar a definição de cada campo
- Padronizar ponto final no final de cada frase.

2024-04-25 13:50 UTC, carolinamenezes commented on docs/faststore/docs/faststore-api/schema/queries.mdx
> +## Query
```suggestion
```

2024-08-13 16:21 UTC, carolinamenezes approved these changes

2024-08-23 20:53 UTC, Mariana-Caetano commented on docs/faststore/docs/faststore-api/schema/enums.mdx
> +## Enums
```suggestion
```

2024-08-23 21:12 UTC, Mariana-Caetano commented on docs/faststore/docs/faststore-api/schema/enums.mdx
> +
```suggestion
```

2024-08-23 21:38 UTC, merged