Update PII guides with Data Protection Plus
vtexdocs/dev-portal-content pull request #1109
Opened 2024-04-30 13:45 UTC by julia-rabello

#### Types of changes
- [ ] New content (guides, endpoints, app documentation)
- [x] Improvement (make a documentation even better)
- [ ] Fix (fix a documentation error)
- [ ] Spelling and grammar accuracy (self-explanatory)

2024-04-30 19:37 UTC, carolinamenezes requested changes

2024-04-30 19:37 UTC, carolinamenezes commented on docs/guides/Integration-Guides/data-privacy/changes-in-vtex-features-behavior-to-handle-pii-data.md
> +> This feature is part of [VTEX Shield](https://help.vtex.com/en/tutorial/vtex-shield--2CVk6H9eY2CBtHjtDI7BFh). If you are already a VTEX customer and want to adopt VTEX Shield for your business, ple
```suggestion
>⚠️ **Closed beta:** [Data Protection Plus](https://developers.vtex.com/docs/guides/data-protection-plus) is in closed beta and is only available in select regions.

>❗ This feature is part of [VTEX Shield](https://help.vtex.com/en/tutorial/vtex-shield--2CVk6H9eY2CBtHjtDI7BFh),  meaning *additional fees may apply.* 
> 
> If you are already a VTEX customer and want to adopt VTEX Shield for your business, please contact [Commercial Support](https://help.vtex.com/en/tracks/support-at-vtex--4AXsGdGHqExp9ZkiNq9eMy/3KQWGgkPOwbFTPfBxL7YwZ).
>
> If you are not yet a customer but are interested in this solution, please complete our [contact form](https://vtex.com/us-en/contact/). 
```

2024-04-30 19:37 UTC, carolinamenezes commented on docs/guides/Integration-Guides/data-privacy/changes-in-vtex-features-behavior-to-handle-pii-data.md
> +> This feature is part of [VTEX Shield](https://help.vtex.com/en/tutorial/vtex-shield--2CVk6H9eY2CBtHjtDI7BFh). If you are already a VTEX customer and want to adopt VTEX Shield for your business, ple
Fiz algumas sugestões para destacar e separar um pouco mais algumas infos importantes.

Em quais regiões está disponível? Senti falta disso

2024-04-30 19:37 UTC, carolinamenezes commented on docs/guides/Integration-Guides/data-privacy/data-protection-plus.md
> +> This feature is part of [VTEX Shield](https://help.vtex.com/en/tutorial/vtex-shield--2CVk6H9eY2CBtHjtDI7BFh). If you are already a VTEX customer and want to adopt VTEX Shield for your business, ple
Mesmo comentário do doc anterior

2024-04-30 19:37 UTC, carolinamenezes commented on docs/guides/Integration-Guides/data-privacy/data-residency.md
> +> This feature is part of [VTEX Shield](https://help.vtex.com/en/tutorial/vtex-shield--2CVk6H9eY2CBtHjtDI7BFh). If you are already a VTEX customer and want to adopt VTEX Shield for your business, ple
+1

2024-04-30 19:37 UTC, carolinamenezes commented on docs/guides/Integration-Guides/data-privacy/erasing-customer-data.md
> +> This feature is part of [VTEX Shield](https://help.vtex.com/en/tutorial/vtex-shield--2CVk6H9eY2CBtHjtDI7BFh). If you are already a VTEX customer and want to adopt VTEX Shield for your business, ple
+1

2024-04-30 19:37 UTC, carolinamenezes commented on docs/guides/Integration-Guides/data-privacy/erasing-customer-data.md
> +>❗ This flow to erase customer data is currently in closed alpha testing stage, meaning that only specific customers can access it now. Do not share this documentation with people outside of your com
Acho que vale juntar com o callout que fala sobre o Closed Beta do Data Protection Plus

2024-04-30 19:37 UTC, carolinamenezes commented on docs/guides/Integration-Guides/data-privacy/limitations-of-the-pii-data-architecture-during-closed-beta.md
> +Some commerce features of the VTEX platform are not available for accounts using the PII data architecture while [Data Protection Plus](https://developers.vtex.com/docs/guides/data-protection-plus) i
A frase ficou um pouco longa. Sugiro dividir para facilitar a leitura

```suggestion
Some commerce features of the VTEX platform are unavailable for accounts using the PII data architecture during the closed beta phase of [Data Protection Plus](https://developers.vtex.com/docs/guides/data-protection-plus). We are actively enhancing this feature to ensure the best data privacy practices across the platform.
```

2024-05-04 00:47 UTC, julia-rabello commented on docs/guides/Integration-Guides/data-privacy/changes-in-vtex-features-behavior-to-handle-pii-data.md
> +> This feature is part of [VTEX Shield](https://help.vtex.com/en/tutorial/vtex-shield--2CVk6H9eY2CBtHjtDI7BFh). If you are already a VTEX customer and want to adopt VTEX Shield for your business, ple
Então, "oficialmente" está disponível para EMEA, mas pelo que conversei com a Aylla, podem ter exceções -- acabaram de implementar em um cliente da América Latina, por exemplo. Por isso, ela e Cae pediram para não especificar a região.

2024-05-06 14:53 UTC, carolinamenezes approved these changes

2024-05-20 20:06 UTC, merged