Fix URL and image - Location Availability
vtexdocs/dev-portal-content pull request #113
Opened 2023-01-10 18:25 UTC by julia-rabello

#### Types of changes
- [ ] New content (guides, endpoints, app documentation)
- [ ] Improvement (make a documentation even better)
- [x] Fix (fix a documentation error)
- [ ] Spelling and grammar accuracy (self-explanatory)

2023-01-10 19:38 UTC, karenkrieger requested changes

2023-01-10 19:38 UTC, karenkrieger commented on docs/vtex-io/Store Framework Apps/b2b-components/vtex-location-availability.md
> +This app provides availability and shipping information based on the user's location, if available at the session, to have a more accurate result, even without authentication. We recommend using this
O link tá dando 404

2023-01-10 20:05 UTC, julia-rabello commented on docs/vtex-io/Store Framework Apps/b2b-components/vtex-location-availability.md
> +This app provides availability and shipping information based on the user's location, if available at the session, to have a more accurate result, even without authentication. We recommend using this
Eu sei, tô tentando consertar essa doc de Shopper Location também. Quando ela estiver no ar, vai ser esse o link 👀

2023-01-12 18:41 UTC, karenkrieger approved these changes
LGTM

2023-01-12 19:02 UTC, merged