EDU-112-86: Section override (Part II)
vtexdocs/dev-portal-content pull request #1136
Opened 2024-05-09 15:37 UTC by Mariana-Caetano

#### Types of changes
- [x] New content (guides, endpoints, app documentation)
- [ ] Improvement (make a documentation even better)
- [ ] Fix (fix a documentation error)
- [ ] Spelling and grammar accuracy (self-explanatory)

- Relates to #1111 
- `navigation.json` updated: [PR 646](https://github.com/vtexdocs/devportal/pull/646) 
- Jira task: [EDU-11286](https://vtex-dev.atlassian.net/browse/EDU-11286)

2024-05-22 21:29 UTC, carolinamenezes requested changes

2024-05-22 21:29 UTC, carolinamenezes commented on docs/faststore/docs/customization/building-sections/overrides/migrating-v1-to-v2.mdx
> +    > ⚠️ If you choose to continue using Section Override v1, please refer to the [Overriding components (v1)](https://developers.vtex.com/docs/guides/faststore/overrides-components-and-props-v1).
Eu acho que deveria ter uma recomendação forte de não usar o v1.

2024-05-22 21:29 UTC, carolinamenezes commented on docs/faststore/docs/customization/building-sections/overrides/migrating-v1-to-v2.mdx
> +| Feature                       | Overrides v1                                           | Overrides v2                                                          |
```suggestion
| Feature                       | Section Override v1                                           | Section Overrides v2                                                          |
```

2024-05-22 21:29 UTC, carolinamenezes commented on docs/faststore/docs/customization/building-sections/overrides/migrating-v1-to-v2.mdx
> +- Previously, in Section Override v1, you defined the override as an object with properties for the section name and component overrides:
```suggestion
- In Section Override v1, a section is overridden by specifying the section name and component:
```

2024-05-22 21:29 UTC, carolinamenezes commented on docs/faststore/docs/customization/building-sections/overrides/migrating-v1-to-v2.mdx
> +Make sure your store's `@faststore/core` package is version 3.0.0 or higher to work with Section Override v2. For update instructions, refer to the [release note](https://github.com/vtex/faststore/re
Me parece o caso de termos um RN no Dev Portal tbm

2024-05-22 21:29 UTC, carolinamenezes commented on docs/faststore/docs/customization/building-sections/overrides/migrating-v1-to-v2.mdx
> +Identify all overrides currently implemented using Overrides v1 (refer to the [Overrides v1](https://developers.vtex.com/docs/guides/faststore/building-sections-overriding-components-and-props) docum
Em alguns lugares tá Overrides e em outros Section Override

2024-05-22 21:29 UTC, carolinamenezes commented on docs/faststore/docs/customization/building-sections/overrides/migrating-v1-to-v2.mdx
> +Identify all overrides currently implemented using Overrides v1 (refer to the [Overrides v1](https://developers.vtex.com/docs/guides/faststore/building-sections-overriding-components-and-props) docum
```suggestion
Identify all overrides currently implemented using Section Override v1 (refer to the [Section Override v1](https://developers.vtex.com/docs/guides/faststore/building-sections-overriding-components-and-props) documentation). Once identified, adjust your code to use Section Override v2.
```

2024-05-22 21:29 UTC, carolinamenezes commented on docs/faststore/docs/customization/building-sections/overrides/migrating-v1-to-v2.mdx
> +Identify all overrides currently implemented using Overrides v1 (refer to the [Overrides v1](https://developers.vtex.com/docs/guides/faststore/building-sections-overriding-components-and-props) docum
Não acho que tem que dar muito espaço para continuar usando v1, não. Isso dificulta a manutenção, etc.
Se quiser usar, ok; mas a gente tá falando para não usar hehe

2024-05-22 21:29 UTC, carolinamenezes commented on docs/faststore/docs/customization/building-sections/overrides/migrating-v1-to-v2.mdx
> +If you wish to maintain existing v1 overrides alongside new v2 overrides, avoid modifying the v1-overridden components. Instead, create new overrides using v2, following the guide on [Overriding a co
```suggestion
```

2024-05-22 21:29 UTC, carolinamenezes commented on docs/faststore/docs/customization/building-sections/overrides/migrating-v1-to-v2.mdx
> +If you wish to maintain existing v1 overrides alongside new v2 overrides, avoid modifying the v1-overridden components. Instead, create new overrides using v2, following the guide on [Overriding a co
Pq?

2024-05-22 21:29 UTC, carolinamenezes commented on docs/faststore/docs/customization/building-sections/overrides/native-component.mdx
> +    > ⚠️ Using overrides does not significantly impact performance. FastStore's handling of props and design tokens is designed for good performance. However, your customizations may introduce additi
Que tipo de customization afeta? Não sei se há necessidade dessa segunda parte
>However, your customizations may introduce additional work, so consider overall store performance by checking Lighthouse reports on GitHub logs and Pull Requests.

2024-05-22 21:29 UTC, carolinamenezes commented on docs/faststore/docs/customization/building-sections/overrides/native-component.mdx
> +6. run the following command to sync your changes with the Headless CMS:
```suggestion
6. Run the following command to sync your changes with the Headless CMS:
```

2024-05-22 21:29 UTC, carolinamenezes commented on docs/faststore/docs/customization/building-sections/overrides/native-component.mdx
> +To see your changes locally you need to set the Headless CMS preview to the development mode.
```suggestion
To see your changes locally, set the Headless CMS preview to the development mode. 
```

2024-05-23 13:24 UTC, Mariana-Caetano commented on docs/faststore/docs/customization/building-sections/overrides/migrating-v1-to-v2.mdx
> +If you wish to maintain existing v1 overrides alongside new v2 overrides, avoid modifying the v1-overridden components. Instead, create new overrides using v2, following the guide on [Overriding a co
Aqui seria mais por não atualizar e migrar de uma vez para v2. A pessoa até pode criar e modificar esses overrides, só não queremos mais porque a intenção é deprecar essa versão e a v2 tem mais esse controle na customização. Porém, não está clara essa frase e o restante da documentação já está reforçando a recomendação de usar a v2.

2024-05-23 13:34 UTC, Mariana-Caetano commented on docs/faststore/docs/customization/building-sections/overrides/migrating-v1-to-v2.mdx
> +Make sure your store's `@faststore/core` package is version 3.0.0 or higher to work with Section Override v2. For update instructions, refer to the [release note](https://github.com/vtex/faststore/re
Concordo! Comecei o draft do PR [aqui](https://github.com/vtexdocs/dev-portal-content/pull/1168).

2024-05-23 14:31 UTC, carolinamenezes approved these changes

2024-05-23 14:39 UTC, merged