Create configuration quick start guide list page
vtexdocs/dev-portal-content pull request #115
Opened 2023-01-10 18:47 UTC by ricardoaerobr

#### Types of changes
- [X] New content (guides, endpoints, app documentation)
- [ ] Improvement (make a documentation even better)
- [ ] Fix (fix a documentation error)
- [ ] Spelling and grammar accuracy (self-explanatory)

Created new Configuration Quick Start Guide List page.

2023-01-10 20:12 UTC, karenkrieger requested changes

2023-01-10 20:12 UTC, karenkrieger commented on docs/guides/Checkout/configuration-section-api-quick-start-guides/get-an-account-orderform-configuration.md
> +---
```suggestion
---

```

2023-01-10 20:12 UTC, karenkrieger commented on docs/guides/Checkout/configuration-section-api-quick-start-guides/get-an-account-orderform-configuration.md
> +[block:code]
```suggestion

```json
```

2023-01-10 20:12 UTC, karenkrieger commented on docs/guides/Checkout/configuration-section-api-quick-start-guides/get-an-account-orderform-configuration.md
> +[/block]
```suggestion
```

```

2023-01-10 20:12 UTC, karenkrieger commented on docs/guides/Checkout/configuration-section-api-quick-start-guides/get-an-account-orderform-configuration.md
> +- **Message error example (code ORD062)**: `"Unauthorized"`. The credentials (Application Key and Application Token) used in this request are incorrect or not authorized to access this type of inform
```suggestion

- **Message error example (code ORD062)**: `"Unauthorized"`. The credentials (Application Key and Application Token) used in this request are incorrect or not authorized to access this type of information.
```

2023-01-10 20:12 UTC, karenkrieger commented on docs/guides/Checkout/configuration-section-api-quick-start-guides/get-an-account-orderform-configuration.md
> +[block:code]
```suggestion

```json
```

2023-01-10 20:12 UTC, karenkrieger commented on docs/guides/Checkout/configuration-section-api-quick-start-guides/get-an-account-orderform-configuration.md
> +[/block]
```suggestion
```

```

2023-01-10 20:12 UTC, karenkrieger commented on docs/guides/Checkout/configuration-section-api-quick-start-guides/get-an-account-orderform-configuration.md
> +[block:code]
```suggestion

```json
```

2023-01-10 20:12 UTC, karenkrieger commented on docs/guides/Checkout/configuration-section-api-quick-start-guides/get-an-account-orderform-configuration.md
> +[/block]
```suggestion
```
```

2023-01-10 20:12 UTC, karenkrieger commented on docs/guides/Checkout/configuration-section-api-quick-start-guides/get-and-update-the-seller-exchange-window.md
> +---
```suggestion
---

```

2023-01-10 20:12 UTC, karenkrieger commented on docs/guides/Checkout/configuration-section-api-quick-start-guides/get-and-update-the-seller-exchange-window.md
> +[block:callout]
Ajustar formato do callout

2023-01-10 20:12 UTC, karenkrieger commented on docs/guides/Checkout/configuration-section-api-quick-start-guides/get-and-update-the-seller-exchange-window.md
> +[block:code]
```suggestion

```json
```

2023-01-10 20:12 UTC, karenkrieger commented on docs/guides/Checkout/configuration-section-api-quick-start-guides/get-and-update-the-seller-exchange-window.md
> +[/block]
```suggestion
```

```

2023-01-10 20:12 UTC, karenkrieger commented on docs/guides/Checkout/configuration-section-api-quick-start-guides/get-and-update-the-seller-exchange-window.md
> +[block:code]
```suggestion

```json
```

2023-01-10 20:12 UTC, karenkrieger commented on docs/guides/Checkout/configuration-section-api-quick-start-guides/get-and-update-the-seller-exchange-window.md
> +[/block]
```suggestion
```

```

2023-01-10 20:12 UTC, karenkrieger commented on docs/guides/Checkout/configuration-section-api-quick-start-guides/get-and-update-the-seller-exchange-window.md
> +[block:code]
```suggestion

```json
```

2023-01-10 20:12 UTC, karenkrieger commented on docs/guides/Checkout/configuration-section-api-quick-start-guides/get-and-update-the-seller-exchange-window.md
> +[/block]
```suggestion
```

```

2023-01-10 20:12 UTC, karenkrieger commented on docs/guides/Checkout/configuration-section-api-quick-start-guides/get-and-update-the-seller-exchange-window.md
> +[block:code]
```suggestion

```json
```

2023-01-10 20:12 UTC, karenkrieger commented on docs/guides/Checkout/configuration-section-api-quick-start-guides/get-and-update-the-seller-exchange-window.md
> +[/block]
```suggestion
```
```

2023-01-10 20:12 UTC, karenkrieger commented on docs/guides/Checkout/configuration-section-api-quick-start-guides/update-an-account-orderform-configuration.md
> +---
```suggestion
---

```

2023-01-10 20:12 UTC, karenkrieger commented on docs/guides/Checkout/configuration-section-api-quick-start-guides/update-an-account-orderform-configuration.md
> +[block:callout]
Formatar callout

2023-01-10 20:12 UTC, karenkrieger commented on docs/guides/Checkout/configuration-section-api-quick-start-guides/update-an-account-orderform-configuration.md
> +[block:code]
```suggestion

```json
```

2023-01-10 20:12 UTC, karenkrieger commented on docs/guides/Checkout/configuration-section-api-quick-start-guides/update-an-account-orderform-configuration.md
> +[/block]
```suggestion

```
```

2023-01-10 20:12 UTC, karenkrieger commented on docs/guides/Checkout/configuration-section-api-quick-start-guides/update-an-account-orderform-configuration.md
> +[block:code]
```suggestion
```json
```

2023-01-10 20:12 UTC, karenkrieger commented on docs/guides/Checkout/configuration-section-api-quick-start-guides/update-an-account-orderform-configuration.md
> +[/block]
```suggestion
```

```

2023-01-10 20:12 UTC, karenkrieger commented on docs/guides/Checkout/configuration-section-api-quick-start-guides/update-an-account-orderform-configuration.md
> +[block:code]
```suggestion

```json
```

2023-01-10 20:12 UTC, karenkrieger commented on docs/guides/Checkout/configuration-section-api-quick-start-guides/update-an-account-orderform-configuration.md
> +[/block]
```suggestion
```
```

2023-01-10 20:27 UTC, ricardoaerobr commented on docs/guides/Checkout/configuration-section-api-quick-start-guides.md
> +This section contains the quick start guides of the endpoints described in the [Configuration section](https://developers.vtex.com/vtex-rest-api/reference/checkout-api-overview#configuration) of the
A referência deste link ficará disponível assim que a modificação do PR-107 for publicada (builder).

2023-01-10 20:31 UTC, ricardoaerobr commented on docs/guides/Checkout/configuration-section-api-quick-start-guides.md
> +- [Clear orderForm message field from cart](https://developers.vtex.com/vtex-rest-api/docs/clear-orderform-message-field-from-cart)
A referência deste link ficará disponível assim que a modificação do PR-115 for aprovada com o novo arquivo (clear-orderform-message-field-from-cart) e publicada (builder).

2023-01-11 13:51 UTC, ricardoaerobr commented on docs/guides/Checkout/configuration-section-api-quick-start-guides.md
> +- [Clear orderForm message field from cart](https://developers.vtex.com/vtex-rest-api/docs/clear-orderform-message-field-from-cart)
Link atualizado e já disponível: https://developers.vtex.com/docs/guides/checkout-api-overview#configuration

2023-01-11 17:54 UTC, ricardoaerobr commented on docs/guides/Checkout/configuration-section-api-quick-start-guides.md
> +This section contains the quick start guides of the endpoints described in the [Configuration section](https://developers.vtex.com/vtex-rest-api/reference/checkout-api-overview#configuration) of the
Link atualizado e já disponível: https://developers.vtex.com/docs/guides/checkout-api-overview#configuration

2023-01-12 18:40 UTC, karenkrieger requested changes

2023-01-12 18:40 UTC, karenkrieger commented on docs/guides/Checkout/configuration-section-api-quick-start-guides/get-an-account-orderform-configuration.md
> +}
```suggestion
}

```

2023-01-12 18:40 UTC, karenkrieger commented on docs/guides/Checkout/configuration-section-api-quick-start-guides/get-and-update-the-seller-exchange-window.md
> +}
```suggestion
}
```
```

2023-01-12 18:40 UTC, karenkrieger commented on docs/guides/Checkout/configuration-section-api-quick-start-guides/get-and-update-the-seller-exchange-window.md
> +}
```suggestion
}
```
```

2023-01-12 18:40 UTC, karenkrieger commented on docs/guides/Checkout/configuration-section-api-quick-start-guides/get-and-update-the-seller-exchange-window.md
> +}
```suggestion
}
```
```

2023-01-12 18:40 UTC, karenkrieger commented on docs/guides/Checkout/configuration-section-api-quick-start-guides/update-an-account-orderform-configuration.md
> +}
```suggestion
}
```
```

2023-01-12 18:40 UTC, karenkrieger commented on docs/guides/Checkout/configuration-section-api-quick-start-guides/update-an-account-orderform-configuration.md
> +}
```suggestion
}
```
```

2023-01-12 18:40 UTC, karenkrieger commented on docs/guides/Checkout/configuration-section-api-quick-start-guides/update-an-account-orderform-configuration.md
> +}
```suggestion
}
```
```

2023-01-13 17:56 UTC, closed without merging