Release note: New @faststore/core package version
vtexdocs/dev-portal-content pull request #1168
Opened 2024-05-23 13:33 UTC by Mariana-Caetano

#### Types of changes
- [x] New content (guides, endpoints, app documentation)
- [ ] Improvement (make a documentation even better)
- [ ] Fix (fix a documentation error)
- [ ] Spelling and grammar accuracy (self-explanatory)

2024-05-27 13:35 UTC, Mariana-Caetano commented on docs/release-notes/2024-05-28-faststore-core-new-version.md
> +Follow the [Best practices for using API extensions](https://developers.vtex.com/docs/faststore/api-extensions-best-practices) guide for more information.
Link quebrado, pois a documentação aestá [neste PR](https://github.com/vtexdocs/dev-portal-content/pull/1175).

2024-06-25 14:23 UTC, carolinamenezes requested changes

2024-06-25 14:23 UTC, carolinamenezes commented on docs/release-notes/2024-05-24-faststore-core-new-version.md
> +FastStore v2 users can now update their`@faststore/core` package version and benefit from enhanced API extensions, streamlined error page customization in the Headless CMS, and support for Next.js 13
```suggestion
FastStore v2 users can now update the `@faststore/core` package version and benefit from enhanced API extensions, streamlined error page customization in the Headless CMS, and support for Next.js 13.
```

2024-06-25 14:23 UTC, carolinamenezes commented on docs/release-notes/2024-05-24-faststore-core-new-version.md
> +To reduce bundle sizes, align with GraphQL community standards, and get up to date with the latest bundling and compilation tools, the latest `@faststore/core` package version 3.0.0 deprecates the `@
```suggestion
To reduce bundle sizes, align with GraphQL community standards, and get up to date with the latest bundling and compilation tools,`@faststore/core` 3.x deprecates the `@faststore/graphql-utils` package in favor of the [`client-preset`](https://the-guild.dev/graphql/codegen/plugins/presets/preset-client) plugin.
```

2024-06-25 14:23 UTC, carolinamenezes commented on docs/release-notes/2024-05-24-faststore-core-new-version.md
> +[gif](/)
Atualizar antes de mergear

2024-06-25 14:23 UTC, carolinamenezes commented on docs/release-notes/2024-05-24-faststore-core-new-version.md
> +Now, these new content types are part of the latest `@faststore/core` package version 3.0, and users can customize them within the Headless CMS.
```suggestion
These content types are now part of the `@faststore/core` 3.x, and users can customize them within the Headless CMS.
```

2024-06-25 14:23 UTC, carolinamenezes commented on docs/release-notes/2024-05-24-faststore-core-new-version.md
> +After running `yarn dev`, update each topic mentioned before as follows:
Cortou?

2024-06-25 14:23 UTC, carolinamenezes commented on docs/release-notes/2024-05-24-faststore-core-new-version.md
Excluir esse arquivo?

2024-06-25 14:23 UTC, carolinamenezes commented on docs/release-notes/2024-06-25-faststore-core-new-version.md
> +To reduce bundle sizes, align with GraphQL community standards, and get up to date with the latest bundling and compilation tools, the latest `@faststore/core` package version 3.0.0 deprecates the `@
```suggestion
To reduce bundle sizes, align with GraphQL community standards, and get up to date with the latest bundling and compilation tools, `@faststore/core` 3.x deprecates the `@faststore/graphql-utils` package in favor of the [`client-preset`](https://the-guild.dev/graphql/codegen/plugins/presets/preset-client) plugin.
```

2024-06-25 14:23 UTC, carolinamenezes commented on docs/release-notes/2024-06-25-faststore-core-new-version.md
> +Now, these new content types are part of the latest `@faststore/core` package version 3.0, and users can customize them within the Headless CMS.
```suggestion
These content types are now part of `@faststore/core` 3.x, and users can customize them within the Headless CMS.
```

2024-06-25 14:23 UTC, carolinamenezes commented on docs/release-notes/2024-06-25-faststore-core-new-version.md
> +   },
```suggestion
   "dependencies": {
      ...
      "next": "^13.5.6",
      ...
   },
```

2024-06-25 14:23 UTC, carolinamenezes commented on docs/release-notes/2024-06-25-faststore-core-new-version.md
> +4. Choose the `EmptyState` section and update its fields according to your store's requirements.
Adicionaria apenas o link para consultar a doc sobre esse tema

2024-08-01 20:11 UTC, Mariana-Caetano commented on docs/release-notes/2024-06-28-faststore-core-new-version.md
> +4. Choose the `EmptyState` section and update its fields according to your store's requirements.
```suggestion
4. Choose the [`EmptyState`](https://developers.vtex.com/docs/guides/faststore/organisms-empty-state) section and update its fields according to your store's requirements.
```

2024-08-01 20:16 UTC, Mariana-Caetano commented on docs/release-notes/2024-06-28-faststore-core-new-version.md
> +slug: "2024-06-28-faststore-core-new-version"
```suggestion
slug: "2024-08-19-faststore-core-new-version"
```

2024-08-13 13:42 UTC, carolinamenezes approved these changes

2024-08-19 22:37 UTC, Mariana-Caetano commented on docs/release-notes/2024-06-28-faststore-core-new-version.md
> +updateAt: "2024-06-26T10:30:00.000Z"
```suggestion
updateAt: "2024-08-19T10:30:00.000Z"
```

2024-08-19 22:41 UTC, merged