feat: new guide for headless CMS
vtexdocs/dev-portal-content pull request #1199
Opened 2024-06-03 17:56 UTC by Mariana-Caetano

#### Types of changes
- [ ] New content (guides, endpoints, app documentation)
- [ ] Improvement (make a documentation even better)
- [ ] Fix (fix a documentation error)
- [ ] Spelling and grammar accuracy (self-explanatory)

2024-06-19 17:40 UTC, carolinamenezes requested changes
A gente não costuma usar "how to", mas sim o verbo no gerúndio. Você pode atualizar a slug e o título da doc para "Previewing..."? 🌻

2024-06-21 18:58 UTC, Mariana-Caetano commented
> Previewing

@carolinamenezes obrigada! Feito ✔

2024-06-21 21:35 UTC, carolinamenezes requested changes

2024-06-21 21:35 UTC, carolinamenezes commented on docs/faststore/docs/headless-cms/previewing-changes-in-development-mode.mdx
> +   localhost:3000/api/preview/?contentType=<contentType>&documentId=<DOCUMENT_ID>&versionId=<VERSION_ID>
```suggestion
   localhost:3000/api/preview/?contentType={contentType}&documentId={documentId}&versionId={versionId}
```

2024-06-21 21:35 UTC, carolinamenezes commented on docs/faststore/docs/headless-cms/previewing-changes-in-development-mode.mdx
> +> ⚠️ Replace `<contentType>`, `<DOCUMENT_ID>`, and `<VERSION_ID>` with the values from your preview link.
```suggestion
        > ⚠️ Replace `{contentType}`, `{documentId}`, and `{versionId}` with the values from your preview link.
```

2024-06-21 21:35 UTC, carolinamenezes commented on docs/faststore/docs/headless-cms/previewing-changes-in-development-mode.mdx
> +1. Open your FastStore project and start a development server.
```suggestion

## Instructions

1. Open your FastStore project and start a development server.
```

2024-06-21 21:35 UTC, carolinamenezes commented on docs/faststore/docs/headless-cms/previewing-changes-in-development-mode.mdx
> +7. Now, access the local preview  by replacing the following parameters accordingly:
```suggestion
7. Now, access the local preview by replacing the following parameters accordingly:
```

2024-06-21 21:35 UTC, carolinamenezes commented on docs/faststore/docs/headless-cms/previewing-changes-in-development-mode.mdx
> +8. Once you have reviewed your changes, terminate the development mode by opening the terminal in the `Developer Tools` and running  the following command in the Headless CMS page:
```suggestion
8. Once you have reviewed your changes, open the terminal in the `Developer Tools` and run the following command in the Headless CMS page to terminate the development mode:
```

2024-06-25 14:24 UTC, carolinamenezes approved these changes

2024-06-25 14:24 UTC, carolinamenezes commented on docs/faststore/docs/headless-cms/previewing-changes-in-development-mode.mdx
> +6. Click on `Preview`. A new tab will open
```suggestion
6. Click the `Preview` button. A new tab will open.
```

2024-06-25 15:19 UTC, merged