EDU-12729 - Updating doc according to LOC review
vtexdocs/dev-portal-content pull request #1302
Opened 2024-07-17 13:31 UTC by barbara-celi

…g-server-side-rendering.md

Updating doc according to LOC review.

[EDU-12729](https://vtex-dev.atlassian.net/browse/EDU-12729)

#### Types of changes
- [ ] New content (guides, endpoints, app documentation)
- [ ] Improvement (make a documentation even better)
- [ ] Fix (fix a documentation error)
- [X] Spelling and grammar accuracy (self-explanatory)

2024-07-17 13:37 UTC, Mariana-Caetano requested changes

2024-07-17 13:37 UTC, Mariana-Caetano commented on docs/faststore/docs/managing-performance/testing-server-side-rendering.md
>  1. Check the documentation of your web browser and search for how to disable JavaScript.
```suggestion
1. Check the documentation of your web browser and search for how to disable JavaScript. For example, if you are using Google Chrome, check Google's documentation on [Disabling JavaScript](https://developers.google.com/web/tools/chrome-devtools/javascript/disable).
```

2024-07-17 13:37 UTC, Mariana-Caetano commented on docs/faststore/docs/managing-performance/testing-server-side-rendering.md
> +   For example, if you are using Google Chrome, check Google's documentation on [Disabling JavaScript](https://developers.google.com/web/tools/chrome-devtools/javascript/disable).
```suggestion
```

2024-07-17 13:37 UTC, Mariana-Caetano commented on docs/faststore/docs/managing-performance/testing-server-side-rendering.md
> +   For example, if you are using Google Chrome, check Google's documentation on [Disabling JavaScript](https://developers.google.com/web/tools/chrome-devtools/javascript/disable).
Sugeri passar essa frase para para o passo 1 por ser uma continuação do passo.

2024-07-17 19:16 UTC, carolinamenezes approved these changes

2024-07-18 13:39 UTC, Mariana-Caetano approved these changes

2024-07-18 14:08 UTC, merged