Fix Pricing Hub + Seller Price docs
vtexdocs/dev-portal-content pull request #137
Opened 2023-01-12 20:03 UTC by julia-rabello

#### Types of changes
- [ ] New content (guides, endpoints, app documentation)
- [ ] Improvement (make a documentation even better)
- [x] Fix (fix a documentation error)
- [ ] Spelling and grammar accuracy (self-explanatory)

2023-01-13 20:21 UTC, karenkrieger requested changes

2023-01-13 20:21 UTC, karenkrieger commented on docs/guides/Integration Guides/pricing-hub/seller-price.md
> +> Make sure to manage the relationship between the marketplace’s catalog and the sellers’ catalogs in the Received SKUs page. Read the article on [Cataloging received SKUs](https://help.vtex.com/en/t
```suggestion
>ℹ️ Make sure to manage the relationship between the marketplace’s catalog and the sellers’ catalogs on the Received SKUs page. Read the article on [Cataloging received SKUs](https://help.vtex.com/en/tutorial/manual-sku-cataloging--tutorials_396) for more information on this process.
```

2023-01-17 16:11 UTC, karenkrieger approved these changes
LGTM

2023-01-17 16:31 UTC, merged

2023-01-17 18:01 UTC, marcellasiqueira approved these changes
LGTM!