EDU-13292: New card component
vtexdocs/dev-portal-content pull request #1391
Opened 2024-09-02 17:56 UTC by Mariana-Caetano

#### Types of changes
- [x] New content (guides, endpoints, app documentation)
- [ ] Improvement (make a documentation even better)
- [ ] Fix (fix a documentation error)
- [ ] Spelling and grammar accuracy (self-explanatory)

2024-09-09 13:59 UTC, henriquessb requested changes

2024-09-09 13:59 UTC, henriquessb commented on docs/faststore/components/molecules/card.mdx
> +
Essa seção deveria existir? Ela só tem uma tabela vazia. Vou deixar a sugestão aqui para remoção.
```suggestion
```

2024-09-09 13:59 UTC, henriquessb commented on docs/faststore/components/molecules/card.mdx
> +Follow the instructions in the [Importing FastStore UI component styles](/docs/customizing/importing-styles-to-faststore-ui-components) tutorial.
Correção do link
```suggestion
Follow the instructions in the [Importing FastStore UI component styles](/docs/guides/faststore/using-themes-importing-ui-components-styles) tutorial.
```

2024-09-09 22:33 UTC, Mariana-Caetano commented on docs/faststore/components/molecules/card.mdx
> +
Ela deveria existir sim, mas no preview que temos para as docs do Developer Portal ele não aparece. A sinformações sobre props dessa tabela são declaradas no próprio arquivo do componente ([aqui](https://github.com/vtex/faststore/blob/main/packages/components/src/molecules/Card/Card.tsx#L6-L27)). Uma vez que publicarmos a doc, ela aparecerá. Algo como [esta do Alert](https://developers.vtex.com/docs/guides/faststore/molecules-alert):
<img width="535" alt="Screenshot_644" src="https://github.com/user-attachments/assets/4b6b12a9-f32e-42fe-b57f-934995164d8d">

2024-09-10 13:45 UTC, henriquessb commented on docs/faststore/components/molecules/card.mdx
> +
Ah entendi. Como vem de outro arquivo, a tabela não aparecia com as props no preview.

2024-09-10 13:45 UTC, henriquessb approved these changes
LGTM

2024-09-12 13:23 UTC, merged