Fix ERP integration guides
vtexdocs/dev-portal-content pull request #149
Opened 2023-01-17 20:00 UTC by julia-rabello

Fix ERP integration guides URLs, images and callouts.

#### Types of changes
- [ ] New content (guides, endpoints, app documentation)
- [ ] Improvement (make a documentation even better)
- [x] Fix (fix a documentation error)
- [ ] Spelling and grammar accuracy (self-explanatory)

2023-01-18 14:49 UTC, marcellasiqueira requested changes

2023-01-18 14:49 UTC, marcellasiqueira commented on docs/guides/Integration Guides/erp-integration-guide/erp-integration-import-inventory.md
>  A basic concept here is that of a **logistics route**, the path connecting your store to the customer. For an order to be placed in a store, the desired item should have stock available in at least o
Não consegui marcar diretamente a linha certa, mas os links de `logistics routes` e `shipping rates` do parágrafo anterior estão quebrados ):

2023-01-18 14:49 UTC, marcellasiqueira commented on docs/guides/Integration Guides/erp-integration-guide/erp-integration-set-up-order-integration.md
> +>⚠️ The feed configuration does not perform any validation on the values inserted. Make sure the elements in the `filter.status` array follow the spelling of the [OMS workflow strings](https://help.v
O link está quebrado

2023-01-18 17:11 UTC, karenkrieger requested changes

2023-01-18 17:11 UTC, karenkrieger commented on docs/guides/Integration Guides/erp-integration-guide/erp-integration-import-products.md
> +> See more details on our [Catalog images integration guide](https://developers.vtex.com/docs/guides/products).
```suggestion
>ℹ️ See more details on our [Catalog images integration guide](https://developers.vtex.com/docs/guides/products).
```

2023-01-19 14:28 UTC, julia-rabello commented on docs/guides/Integration Guides/erp-integration-guide.md
> +> Make sure you've gone through our [Getting Started Guide](https://developers.vtex.com/docs/guides/getting-started-platform-overview) and have [created the appKey and appToken](https://developers.vt
@marcellasiqueira como faço para fazer quebra de linha dentro do callout?

2023-01-19 14:33 UTC, julia-rabello commented on docs/guides/Integration Guides/erp-integration-guide/erp-integration-set-up-order-integration.md
> +>⚠️ The feed configuration does not perform any validation on the values inserted. Make sure the elements in the `filter.status` array follow the spelling of the [OMS workflow strings](https://help.v
fixed!

2023-01-19 15:54 UTC, karenkrieger approved these changes
LGTM

2023-01-19 18:51 UTC, julia-rabello commented on docs/guides/Integration Guides/erp-integration-guide.md
> +> Make sure you've gone through our [Getting Started Guide](https://developers.vtex.com/docs/guides/getting-started-platform-overview) and have [created the appKey and appToken](https://developers.vt
@karenkrieger sugeriu fazer assim:

```
> Make sure you've gone through our [Getting Started Guide](https://developers.vtex.com/docs/guides/getting-started-platform-overview) and have [created the appKey and appToken](https://developers.vtex.com/docs/guides/getting-started-authentication#application-keys) for the system you want to integrate with VTEX.
> 
> For stores hosted in Seller Portal or Admin v4, you can find the Application Keys page by clicking on your **profile's avatar**, marked with the initial from your email, then going to **Account settings > Application keys.**
```

2023-01-25 00:27 UTC, marcellasiqueira approved these changes

2023-01-25 13:31 UTC, merged