Fix catalog-api-overview.md
vtexdocs/dev-portal-content pull request #152
Opened 2023-01-17 21:08 UTC by julia-rabello

#### Types of changes
- [ ] New content (guides, endpoints, app documentation)
- [ ] Improvement (make a documentation even better)
- [x] Fix (fix a documentation error)
- [ ] Spelling and grammar accuracy (self-explanatory)

2023-01-18 15:02 UTC, marcellasiqueira requested changes

2023-01-18 17:35 UTC, karenkrieger requested changes
`+ 1` no comentário da @marcellasiqueira

2023-01-19 14:39 UTC, julia-rabello commented on docs/guides/Catalog/catalog-api-overview.md
>  - [Category Subcollection](ref:catalog-api-category-subcollection) - Here you can associate or disassociate  a subcollection to a category.
era para ter removido esse tópico. corrigi agora!

2023-01-19 15:55 UTC, karenkrieger approved these changes
LGTM

2023-01-25 00:27 UTC, marcellasiqueira approved these changes

2023-01-25 13:31 UTC, merged