Fix catalog-api-seller-portal-overview.md
vtexdocs/dev-portal-content pull request #153
Opened 2023-01-17 21:17 UTC by julia-rabello

#### Types of changes
- [ ] New content (guides, endpoints, app documentation)
- [ ] Improvement (make a documentation even better)
- [x] Fix (fix a documentation error)
- [ ] Spelling and grammar accuracy (self-explanatory)

2023-01-18 15:07 UTC, marcellasiqueira requested changes

2023-01-18 15:07 UTC, marcellasiqueira commented on docs/guides/Catalog Seller Portal/catalog-api-seller-portal-overview.md
> +`GET` [Get Product by external ID, SKU ID, SKU external ID or slug](https://developers.vtex.com/docs/api-reference/catalog-api-seller-portal#get-/api/catalog-seller-portal/products/-param-)
o link em `Get Product by external ID, SKU ID, SKU external ID or slug` tá correto mesmo? fiquei na dúvida 😅

2023-01-18 17:49 UTC, karenkrieger requested changes

2023-01-18 17:49 UTC, karenkrieger commented on docs/guides/Catalog Seller Portal/catalog-api-seller-portal-overview.md
> +`GET` [Get Product by external ID, SKU ID, SKU external ID or slug](https://developers.vtex.com/docs/api-reference/catalog-api-seller-portal#get-/api/catalog-seller-portal/products/-param-)
Ele não tá abrindo o link do endpoint

2023-01-19 18:40 UTC, karenkrieger approved these changes
LGTM

2023-01-25 00:27 UTC, marcellasiqueira approved these changes

2023-01-25 13:31 UTC, merged