Move Marketplace API overview and fix formatting
vtexdocs/dev-portal-content pull request #154
Opened 2023-01-17 21:27 UTC by julia-rabello

#### Types of changes
- [ ] New content (guides, endpoints, app documentation)
- [ ] Improvement (make a documentation even better)
- [x] Fix (fix a documentation error)
- [ ] Spelling and grammar accuracy (self-explanatory)

2023-01-18 15:17 UTC, marcellasiqueira requested changes

2023-01-18 15:17 UTC, marcellasiqueira commented on docs/guides/Marketplace/marketplace-api-overview.md
> +`GET`[Get SKU’s review information](https://developers.vtex.com/vtex-rest-api/reference/getreview)
link quebrado

2023-01-18 17:55 UTC, karenkrieger requested changes
`+ 1` nos comentários da @marcellasiqueira

2023-01-19 14:46 UTC, julia-rabello commented
Parece que esse trecho estava desatualizado, os endpoints não existem mais. Removi da overview.

2023-01-19 15:57 UTC, karenkrieger approved these changes
LGTM

2023-01-25 00:27 UTC, marcellasiqueira approved these changes

2023-01-25 13:30 UTC, merged