EDU-13542: FastStore Analytics - `sendAnalyticsEvent`
vtexdocs/dev-portal-content pull request #1544
Opened 2024-11-08 17:36 UTC by Mariana-Caetano

#### Types of changes
- [x] New content (guides, endpoints, app documentation)
- [ ] Improvement (make a documentation even better)
- [ ] Fix (fix a documentation error)
- [ ] Spelling and grammar accuracy (self-explanatory)

2024-11-11 14:23 UTC, carolinamenezes requested changes

2024-11-11 14:23 UTC, carolinamenezes commented on docs/localization/send-analytics-event.md
> +Check the list of [Available types](/LINK).
Ficou faltando o link aqui

2024-11-11 15:56 UTC, Mariana-Caetano commented on docs/localization/send-analytics-event.md
> +Check the list of [Available types](/LINK).
Boa, Carol! 
🎗️ Após a revisão de LOC nesse PR e do `sendAnalytics`, adicionar o link correto: https://github.com/vtexdocs/dev-portal-content/pull/1534

2024-11-26 13:22 UTC, Mariana-Caetano commented
Closing this PR and moving the doc to the https://github.com/vtexdocs/dev-portal-content/pull/1534

2024-11-26 13:22 UTC, closed without merging