Fix vtex-tracking-overview.md
vtexdocs/dev-portal-content pull request #159
Opened 2023-01-17 22:24 UTC by julia-rabello

#### Types of changes
- [ ] New content (guides, endpoints, app documentation)
- [ ] Improvement (make a documentation even better)
- [x] Fix (fix a documentation error)
- [ ] Spelling and grammar accuracy (self-explanatory)

2023-01-18 18:22 UTC, karenkrieger requested changes

2023-01-18 18:22 UTC, karenkrieger commented on docs/guides/VTEX Tracking/vtex-tracking-overview.md
> +`POST` [Asynchronous Login](https://developers.vtex.com/vtex-developer-docs/reference/vtex-tracking-api-authentication)
Link quebrado

2023-01-18 18:38 UTC, marcellasiqueira requested changes
mesmo comentário da @karenkrieger

2023-01-19 15:59 UTC, karenkrieger approved these changes
LGTM

2023-01-25 00:26 UTC, marcellasiqueira approved these changes

2023-01-25 13:30 UTC, merged