EDU-13251 - Configuring templates
vtexdocs/dev-portal-content pull request #1609
Opened 2024-11-27 17:38 UTC by barbara-celi

#### Types of changes
- [ ] New content (guides, endpoints, app documentation)
- [X] Improvement (make a documentation even better)
- [ ] Fix (fix a documentation error)
- [ ] Spelling and grammar accuracy (self-explanatory)

[EDU-13251](https://vtex-dev.atlassian.net/browse/EDU-13251)

[EDU-13251]: https://vtex-dev.atlassian.net/browse/EDU-13251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-11-28 14:51 UTC, barbara-celi commented on docs/guides/vtex-io/Getting-Started/getting-started-3/vtex-io-documentation-4-configuringtemplates.md
> +> ℹ Learn more about these and other relevant concepts in [Essential concepts](LINK).
Pensei em pegar as docs que ainda existem na categoria *Concepts* e criar um único guia, visto que os conceitos ali dialogam bastante. Coloquei o nome de *Essential concepts*, mas é provisório. Posso ver depois um título melhor.

As docs que ainda estão lá são: [Composition](https://developers.vtex.com/docs/guides/vtex-io-documentation-composition), [Interfaces](https://developers.vtex.com/docs/guides/vtex-io-documentation-interface), [Properties](https://developers.vtex.com/docs/guides/vtex-io-documentation-properties) e [Slots](https://developers.vtex.com/docs/guides/vtex-io-documentation-slots).

2025-01-06 17:12 UTC, carolinamenezes commented on docs/guides/vtex-io/Getting-Started/getting-started-3/vtex-io-documentation-4-configuringtemplates.md
> +In this guide, you will learn how to customize your store theme by managing templates, which are the website’s page structure. Templates are responsible for declaring `JSON` blocks that, once rendere
```suggestion
In this guide, you will learn how to customize your store theme by managing templates, which are the website’s page structure. Templates are responsible for declaring `JSON` blocks that, once rendered, define the set of components for your website's pages, such as the homepage, product page, search results page, etc.
```

2025-01-06 17:16 UTC, carolinamenezes requested changes
Atualização do link pendente

2025-01-06 17:16 UTC, carolinamenezes commented on docs/guides/vtex-io/Getting-Started/getting-started-3/vtex-io-documentation-4-configuringtemplates.md
> +> ℹ Learn more about these and other relevant concepts in [Essential concepts](LINK).
Boa! Mesmo que não fique em um único doc, pode ser o link para a categoria mãe delas.

Para essa tarefa não ficar travada, acho melhor manter os links que temos e criar uma nova tarefa para lembrar de atualizar aqui quando tivermos essas docs organizadas

2025-01-06 17:16 UTC, carolinamenezes commented on docs/guides/vtex-io/Getting-Started/getting-started-3/vtex-io-documentation-4-configuringtemplates.md
> +>⚠ More than simply declaring a block in the block list template, you also need to define its behavior when rendered as a component. To do this, use the block's props, as shown in the [Clarifying blo
```suggestion
>⚠ More than simply declaring a block in the block list template, you also need to define its behavior when rendered as a component. To do this, use the block's props, as shown in the [Clarifying block naming and properties](#clarifying-block-naming-and-properties) section, and include other child blocks to define its configuration, as detailed in the [Defining blocks composition](#defining-blocks-composition).
```

2025-02-04 19:31 UTC, carolinamenezes reviewed
Eu só não tiraria "Step x - " dos subtitulos dentro de **Instructions**. Eu particularmente gosto porque me dá um senso de sequência. Acho até que dá para discutir isso porque acaba sendo uma preferência minha mesmo

2025-02-05 13:24 UTC, carolinamenezes approved these changes

2025-02-05 13:41 UTC, merged