EDU-14042: Add `useScreenResize` to list of experimental hook
vtexdocs/dev-portal-content pull request #1650
Opened 2024-12-30 15:40 UTC by mariana-caetano

#### Types of changes
- [ ] New content (guides, endpoints, app documentation)
- [X] Improvement (make a documentation even better)
- [ ] Fix (fix a documentation error)
- [ ] Spelling and grammar accuracy (self-explanatory)

2024-12-30 15:42 UTC, mariana-caetano commented on docs/faststore/docs/customization/building-sections/experimental-exports-hooks-and-components.mdx
> +| `useScreenResize` | Creates more flexible interfaces that adapt to different screen sizes and devices.|
```suggestion
| `useScreenResize_unstable` | Creates more flexible interfaces that adapt to different screen sizes and devices.|
```

2025-01-02 14:07 UTC, carolinamenezes requested changes

2025-01-02 14:07 UTC, carolinamenezes commented on docs/faststore/docs/customization/building-sections/experimental-exports-hooks-and-components.mdx
> +| `useScreenResize_unstable` | Creates more flexible interfaces that adapt to different screen sizes and devices.|
```suggestion
| `useScreenResize_unstable` | Adapts the interface to different screen sizes and devices.|
```

2025-01-02 15:04 UTC, hellofanny commented on docs/faststore/docs/customization/building-sections/experimental-exports-hooks-and-components.mdx
> +| `useScreenResize_unstable` | Adapts the interface to different screen sizes and devices.|
```suggestion
|`useScreenResize_unstable` | Adapts the interface to different screen sizes and devices.|
```

2025-01-02 15:04 UTC, hellofanny approved these changes

2025-01-02 17:20 UTC, carolinamenezes approved these changes

2025-01-02 17:26 UTC, merged