Updating doc with details on create channel endpoint and corrected links
vtexdocs/dev-portal-content pull request #236
Opened 2023-02-08 21:09 UTC by jumeyermattosarruda

#### Types of changes
- [ ] New content (guides, endpoints, app documentation)
- [x] Improvement (make a documentation even better)
- [ ] Fix (fix a documentation error)
- [ ] Spelling and grammar accuracy (self-explanatory)

Added more details about creating channels based on this [issue](https://github.com/vtexdocs/dev-portal-content/issues/218) created.
Also corrected links with new URLs.

2023-02-09 14:47 UTC, jumeyermattosarruda commented on docs/guides/Integration-Guides/sent-offers-integration-guide-connectors.md
> +After the [channel is created](https://developers.vtex.com/docs/api-reference/marketplace-apis-offer-management#post-/api/sent-offers/channels), the connection between seller and marketplace can be e
É porque esse é o passo 2 de uma sequência de ações, e o heading acima dele fala só sobre a etapa de criação do channel. Então pra chegar no passo 2, obrigatoriamente o passo 1 precisa ter sido cumprido. Vou linkar pro heading ao invés d aAPI ref, e dar uma modificada

2023-02-09 15:04 UTC, jumeyermattosarruda commented on docs/guides/Integration-Guides/sent-offers-integration-guide-connectors.md
> +1. [Create Channel](https://developers.vtex.com/docs/api-reference/marketplace-apis-offer-management#post-/api/sent-offers/channels)
Não! Corrigido

2023-02-09 15:26 UTC, jumeyermattosarruda commented on docs/guides/Integration-Guides/sent-offers-integration-guide-connectors.md
>  > **API Reference:** Activate Feed
Feito!

2023-02-09 16:57 UTC, julia-rabello requested changes

2023-02-09 16:57 UTC, julia-rabello commented on docs/guides/Integration-Guides/sent-offers-integration-guide-connectors.md
> +1. [Creating channel](#1--create-channel).
```suggestion
1. [Creating channel](#1-create-channel).
```

2023-02-09 16:57 UTC, julia-rabello commented on docs/guides/Integration-Guides/sent-offers-integration-guide-connectors.md
> +2. [Activating feed](#2--feed-establishing-the-connection).
```suggestion
2. [Activating feed](#2-feed-establishing-the-connection).
```

2023-02-09 16:57 UTC, julia-rabello commented on docs/guides/Integration-Guides/sent-offers-integration-guide-connectors.md
> +After you have [created the channel](#1--create-channel) in Offer Management, the connection between seller and marketplace can be established, through the feed. The channels available for connecting
```suggestion
After you have [created the channel](#1-create-channel) in Offer Management, the connection between seller and marketplace can be established, through the feed. The channels available for connecting with Offer Management are:
```

2023-02-09 16:57 UTC, julia-rabello commented on docs/guides/Integration-Guides/sent-offers-integration-guide-connectors.md
> +> **API Reference:** [Open Interaction](https://developers.vtex.com/docs/api-reference/marketplace-apis-offer-management#post-/api/sent-offers/feeds/-feedId-/skus/-skuId-/interactions), [Close Intera
```suggestion
> **API Reference:** [Open Interaction](https://developers.vtex.com/docs/api-reference/marketplace-apis-offer-management#post-/api/sent-offers/feeds/-feedId-/skus/-skuId-/interactions), [Close Interaction](https://developers.vtex.com/docs/api-reference/marketplace-apis-offer-management#post-/api/sent-offers/feeds/-feedId-/skus/-skuId-/interactions/-interactionId-/close)
```

2023-02-09 16:57 UTC, julia-rabello commented on docs/guides/Integration-Guides/sent-offers-integration-guide-connectors.md
> +> **API Reference:** [Create Log](https://developers.vtex.com/docs/api-reference/marketplace-apis-offer-management#post-/api/sent-offers/feeds/-feedId-/skus/-skuId-/interactions/-interactionId-/logs)
```suggestion
> **API Reference:** [Create Log](https://developers.vtex.com/docs/api-reference/marketplace-apis-offer-management#post-/api/sent-offers/feeds/-feedId-/skus/-skuId-/interactions/-interactionId-/logs)
```

2023-02-09 19:55 UTC, jumeyermattosarruda commented on docs/guides/Integration-Guides/sent-offers-integration-guide-connectors.md
> +1. [Creating channel](#1--create-channel).
Qualquer caractere é transformado em `-` na slug. Como o heading é 1. Create Channel, esse caractere vira (#1--create-channel)

2023-02-10 00:10 UTC, julia-rabello commented on docs/guides/Integration-Guides/sent-offers-integration-guide-connectors.md
> +1. [Creating channel](#1--create-channel).
Pontos são ignorados, assim como vírgulas e dois pontos. Testei nessa doc mesmo:
- [https://developers.vtex.com/docs/guides/sent-offers-integration-guide-connectors#1-create-channel](https://developers.vtex.com/docs/guides/sent-offers-integration-guide-connectors#1-create-channel) funciona
- [https://developers.vtex.com/docs/guides/sent-offers-integration-guide-connectors#1--create-channel](https://developers.vtex.com/docs/guides/sent-offers-integration-guide-connectors#1--create-channel) não funciona

2023-02-10 13:42 UTC, merged