Getting started/making your first request/update
vtexdocs/dev-portal-content pull request #237
Opened 2023-02-09 00:10 UTC by PedroAntunesCosta

I have rewritten the guide Making your first request to match the reality of our current dev portal.

#### Types of changes
- [ ] New content (guides, endpoints, app documentation)
- [x] Improvement (make a documentation even better)
- [ ] Fix (fix a documentation error)
- [ ] Spelling and grammar accuracy (self-explanatory)

2023-02-10 14:02 UTC, carolinamenezes commented
Obs.: Atualizando a slug da doc, lembrar de atualizar o `navigation.json` e adicionar o redirect correspondente

2023-02-10 14:57 UTC, carolinamenezes approved these changes
Caprichou ✨🚀
Deixei algumas sugestões para você dar uma olhada, mas LGTM

2023-02-10 14:57 UTC, carolinamenezes commented on docs/guides/Getting-Started/getting-started/making-your-first-request.md
> +Each request to VTEX APIs [must be authenticated](https://developers.vtex.com/docs/guides/getting-started-authentication). And to use the Developers Portal `TEST METHOD`, you must use [application ke
```suggestion
Every request to VTEX APIs [must be authenticated](https://developers.vtex.com/docs/guides/getting-started-authentication), either through application keys or user tokens. In the Developers Portal, the `TEST METHOD` requires a pair of an `appKey` and an `appToken`.
```

2023-02-10 14:57 UTC, carolinamenezes commented on docs/guides/Getting-Started/getting-started/making-your-first-request.md
> +So before going forward with this tutorial, make sure you have a app key and token pair with the right [permissions](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc). If you do not ha
```suggestion
Hence, before proceeding with this guide, make sure you have a valid pair of `appKey` and appToken` with the necessary [permissions](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc) to execute the requests you want. If you do not have this credential yet, learn more about how to [create application keys](https://help.vtex.com/en/tutorial/application-keys--2iffYzlvvz4BDMr6WGUtet).
```

2023-02-10 14:57 UTC, carolinamenezes commented on docs/guides/Getting-Started/getting-started/making-your-first-request.md
> +>ℹ️ Some API requests may return other status codes in case of success, such as `201 Created` or `204 No Content`.
Talvez essa parte possa vir em uma outra seção (e.g., handling http status codes) no final da doc e mencionada aqui

2023-02-10 14:57 UTC, carolinamenezes commented on docs/guides/Getting-Started/getting-started/making-your-first-request.md
> +## Exporting API information
```suggestion
## Using an API testing platform
```

2023-02-10 14:57 UTC, carolinamenezes commented on docs/guides/Getting-Started/getting-started/making-your-first-request.md
> +You can export API specification or example requests to be used with [Postman](#using-postman) or the API platform of your choice.
```suggestion
You can export an API specification or example request to use with [Postman](#using-postman) or the API platform of your choice.
```

2023-02-10 14:57 UTC, carolinamenezes commented on docs/guides/Getting-Started/getting-started/making-your-first-request.md
> +This means you can copy this content to be imported into other software.
Acho que essa parte poderia vir no final. Só faz sentido o usuário copiar a request depois de ter exportado as especificações, nopes?

2023-02-10 14:57 UTC, carolinamenezes commented on docs/guides/Getting-Started/getting-started/making-your-first-request.md
> +### Downloading API specifications
Não vejo necessidade desse título aqui caso considere a sugestão anterior

2023-02-10 15:02 UTC, carolinamenezes commented on docs/guides/Getting-Started/getting-started/making-your-first-request.md
> +![List orders page](./making-your-first-request-1)
Faltou indicar os formatos das imagens

2023-02-10 15:03 UTC, carolinamenezes requested changes
Faltou indicar os formatos das imagens. Exemplo

`![List orders page](./making-your-first-request-1)` > `![List orders page](./making-your-first-request-1.png)`

2023-02-13 21:07 UTC, PedroAntunesCosta commented on docs/guides/Getting-Started/getting-started/making-your-first-request.md
> +>ℹ️ Some API requests may return other status codes in case of success, such as `201 Created` or `204 No Content`.
Pode ser, mas a princípio enxergo como parte do passo-a-passo. 🤔

2023-02-13 21:12 UTC, PedroAntunesCosta commented on docs/guides/Getting-Started/getting-started/making-your-first-request.md
> +This means you can copy this content to be imported into other software.
Entendo como duas formas paralelas de exportar request pra trazer pro postman. Se baixou o OAS e importou no Postman, nãoprecisa copiar o exemplo de código

2023-02-13 21:24 UTC, PedroAntunesCosta commented on docs/guides/Getting-Started/getting-started/making-your-first-request.md
> +Each request to VTEX APIs [must be authenticated](https://developers.vtex.com/docs/guides/getting-started-authentication). And to use the Developers Portal `TEST METHOD`, you must use [application ke
Boa! Implementei com adaptações

2023-02-13 21:25 UTC, PedroAntunesCosta commented
> Obs.: Atualizando a slug da doc, lembrar de atualizar o `navigation.json` e adicionar o redirect correspondente

Fiz isso nesse [PR aqui](https://github.com/vtexdocs/devportal/pull/233), @carolinamenezes !

2023-02-13 23:27 UTC, carolinamenezes approved these changes

2023-02-14 12:39 UTC, merged