Create vtex-shipping-network-labels-integration.md
vtexdocs/dev-portal-content pull request #275
Opened 2023-03-01 20:23 UTC by Isabella-Veloso

#### Types of changes
- [x] New content (guides, endpoints, app documentation)
- [ ] Improvement (make a documentation even better)
- [ ] Fix (fix a documentation error)
- [ ] Spelling and grammar accuracy (self-explanatory)

Documentation for VTEX Shipping Network labels integration for the closed beta. It will be shared with only a couple of clients for feedback and iteration. The documentation was created by the team, and I have made a basic review.

2023-03-01 23:08 UTC, jumeyermattosarruda requested changes

2023-03-01 23:08 UTC, jumeyermattosarruda commented on docs/guides/Integration-Guides/vtex-shipping-network/vtex-shipping-network-labels-integration.md
> +The following lifecycle overview of a Package created in the VTEX Shipping Network module (SPN) will provide an overview of these workflows:
```suggestion
 A Package created in the VTEX Shipping Network module (SPN) has the following lifecycle, including these workflows:
```

2023-03-01 23:08 UTC, jumeyermattosarruda commented on docs/guides/Integration-Guides/vtex-shipping-network/vtex-shipping-network-labels-integration.md
> +2. The Carrier App will then receive a notification request for all packages, and their status will move to `carrier_notified`.
Dá pra adicionar o link do Carrier App aqui. Tá publicada a doc?

2023-03-01 23:08 UTC, jumeyermattosarruda commented on docs/guides/Integration-Guides/vtex-shipping-network/vtex-shipping-network-labels-integration.md
> +Be aware that VTEX Shipping Network only keeps track of Fulfillment orders, therefore, the `orderId` used on the endpoint must have their origin as Fulfillment. All Fulfillment Orders contain a prefi
Temos link pra explicar mais sobre o que são fulfillment orders?

2023-03-01 23:08 UTC, jumeyermattosarruda commented on docs/guides/Integration-Guides/vtex-shipping-network/vtex-shipping-network-labels-integration.md
> +Be aware that VTEX Shipping Network only keeps track of Fulfillment orders, therefore, the `orderId` used on the endpoint must have their origin as Fulfillment. All Fulfillment Orders contain a prefi
Tinha pensado em algo como [aqui](https://developers.vtex.com/docs/guides/multilevel-omnichannel-inventory#order-flow), mas não tem a terminologia de Fulfillment orders nessa doc de MOI

2023-03-02 14:05 UTC, Isabella-Veloso commented on docs/guides/Integration-Guides/vtex-shipping-network/vtex-shipping-network-labels-integration.md
> +Be aware that VTEX Shipping Network only keeps track of Fulfillment orders, therefore, the `orderId` used on the endpoint must have their origin as Fulfillment. All Fulfillment Orders contain a prefi
Feito.

2023-03-02 16:31 UTC, merged