Complete editorial update
vtexdocs/dev-portal-content pull request #357
Opened 2023-04-12 20:06 UTC by ricardoaerobr

#### Types of changes
- [ ] New content (guides, endpoints, app documentation)
- [X] Improvement (make a documentation even better)
- [ ] Fix (fix a documentation error)
- [ ] Spelling and grammar accuracy (self-explanatory)

PR created to fix broken links and callout formats, and make editorial improvements to the article "Pix: Instant Payments in Brazil" (EDU-9714).

2023-04-14 18:59 UTC, karenkrieger requested changes

2023-04-14 18:59 UTC, karenkrieger commented on docs/guides/Integration-Guides/payments-integration-guide/payments-integration-pix-instant-payments-in-brazil.md
>  [block:callout]
Formatar callout

2023-04-14 18:59 UTC, karenkrieger commented on docs/guides/Integration-Guides/payments-integration-guide/payments-integration-pix-instant-payments-in-brazil.md
> +- [Configuration Flow endpoints](https://developers.vtex.com/docs/api-reference/payment-provider-protocol#post-/authorization/token): 3 endpoints whose implementation is **optional and currently not
```suggestion
- [Configuration Flow endpoints](https://developers.vtex.com/docs/api-reference/payment-provider-protocol#post-/authorization/token): three endpoints whose implementation is **optional and currently not available for Pix**.
```

2023-04-14 18:59 UTC, karenkrieger commented on docs/guides/Integration-Guides/payments-integration-guide/payments-integration-pix-instant-payments-in-brazil.md
>  [block:parameters]
Formatar código

2023-04-14 18:59 UTC, karenkrieger commented on docs/guides/Integration-Guides/payments-integration-guide/payments-integration-pix-instant-payments-in-brazil.md
> +For more information about the Pix, access its [FAQ](https://help.vtex.com/pt/tutorial/pix-faq--3lx7zCU2lQroTEBCYKYbo3).
```suggestion
For more information about the Pix, access its [FAQ](https://help.vtex.com/en/tutorial/pix-faq--3lx7zCU2lQroTEBCYKYbo3).
```

2023-04-14 19:45 UTC, ricardoaerobr commented on docs/guides/Integration-Guides/payments-integration-guide/payments-integration-pix-instant-payments-in-brazil.md
> +For more information about the Pix, access its [FAQ](https://help.vtex.com/pt/tutorial/pix-faq--3lx7zCU2lQroTEBCYKYbo3).
Fixed.

2023-04-14 19:46 UTC, ricardoaerobr commented on docs/guides/Integration-Guides/payments-integration-guide/payments-integration-pix-instant-payments-in-brazil.md
> +- [Configuration Flow endpoints](https://developers.vtex.com/docs/api-reference/payment-provider-protocol#post-/authorization/token): 3 endpoints whose implementation is **optional and currently not
Fixed.

2023-04-17 12:00 UTC, ricardoaerobr commented on docs/guides/Integration-Guides/payments-integration-guide/payments-integration-pix-instant-payments-in-brazil.md
>  [block:callout]
Fixed.

2023-04-17 12:01 UTC, ricardoaerobr commented on docs/guides/Integration-Guides/payments-integration-guide/payments-integration-pix-instant-payments-in-brazil.md
>  [block:parameters]
Fixed.

2023-04-17 18:07 UTC, karenkrieger requested changes

2023-04-17 18:08 UTC, karenkrieger approved these changes
LGTM

2023-04-17 18:31 UTC, merged