Fixes of i18n on get-and-update-the-seller-exchange-window.md
vtexdocs/dev-portal-content pull request #473
Opened 2023-05-22 12:12 UTC by GeorgeLimaDev

It relates to task [LOC-10435](https://vtex-dev.atlassian.net/browse/LOC-10435) and KR 23Q2-KR1 ([Review all developer portal documentation in English](https://docs.google.com/document/d/1VduAYpjqdazhyGH5DvD9c52pMu1Xfj4RDx48QNjTFU0/edit)).

#### Types of changes
- [ ] New content (guides, endpoints, app documentation)
- [ ] Improvement (make a documentation even better)
- [ ] Fix (fix a documentation error)
- [X] Spelling and grammar accuracy (self-explanatory)

2023-05-22 12:32 UTC, ricardoaerobr commented on docs/guides/Checkout/configuration-section-api-quick-start-guides/get-and-update-the-seller-exchange-window.md
> +To get seller change window in a marketplace, you need to use the [Get window to change seller](https://developers.vtex.com/vtex-rest-api/reference/getwindowtochangeseller) endpoint as a **GET** requ
Atualizar link: [Get window to change seller](https://developers.vtex.com/docs/api-reference/checkout-api#get-/api/checkout/pvt/configuration/window-to-change-seller)

2023-05-22 12:32 UTC, ricardoaerobr commented on docs/guides/Checkout/configuration-section-api-quick-start-guides/get-and-update-the-seller-exchange-window.md
> +To update the seller change window (in days), you need to use a request similar to **Get window to change seller**, but as a **POST** request ([Update window to change seller](https://developers.vtex
Atualizar link: [Update window to change seller](https://developers.vtex.com/docs/api-reference/orders-api#post-/api/checkout/pvt/configuration/window-to-change-seller)

2023-05-22 12:32 UTC, ricardoaerobr commented on docs/guides/Checkout/configuration-section-api-quick-start-guides/get-and-update-the-seller-exchange-window.md
> +To confirm that the new seller change window has been applied to your account, access the [Get window to change seller](https://developers.vtex.com/vtex-rest-api/reference/getwindowtochangeseller) en
Atualizar link: [Get window to change seller](https://developers.vtex.com/docs/api-reference/checkout-api#get-/api/checkout/pvt/configuration/window-to-change-seller)

2023-06-12 14:06 UTC, carolinamenezes commented on docs/guides/Checkout/configuration-section-api-quick-start-guides/get-and-update-the-seller-exchange-window.md
> +> ⚠️ The default window for changing a seller is <strong>2 days</strong>. However, you can change it for up to <strong>30 days</strong>.
```suggestion

> ⚠️ The default window for changing a seller is **2 days**. However, you can change it for up to **30 days**.
```

2023-06-12 14:07 UTC, carolinamenezes commented on docs/guides/Checkout/configuration-section-api-quick-start-guides/get-and-update-the-seller-exchange-window.md
>  ```json
```suggestion
```html
```

2023-06-15 19:41 UTC, julia-rabello requested changes

2023-06-15 19:41 UTC, julia-rabello commented on docs/guides/Checkout/configuration-section-api-quick-start-guides/get-and-update-the-seller-exchange-window.md
> +[Marketplace](https://help.vtex.com/en/tutorial/integrating-with-marketplace) is a platform where different sellers can sell their products in a single place. After the customer makes a purchase and
```suggestion
A [Marketplace](https://help.vtex.com/en/tutorial/integrating-with-marketplace) is a platform where products from different sellers can be offered to customers in a single place. After the customer makes a purchase and the order is created, there may be scenarios in which the original seller of the product needs to be modified, for example, when they cancel the order due to internal unavailability of product fulfillment.
```

2023-06-15 19:41 UTC, julia-rabello commented on docs/guides/Checkout/configuration-section-api-quick-start-guides/get-and-update-the-seller-exchange-window.md
> +In such situations, VTEX allows the marketplace to have a period (window) after the customer makes the purchase to change sellers and avoid order cancellation. For more information on the process of
```suggestion
In such situations, after the customer makes the purchase, VTEX allows the marketplace to have a period of time (window) to change sellers and avoid order cancellation. For more information on the process of changing sellers, please read the guides in the [Help Center](https://help.vtex.com/en/tutorial/change-seller--5TBAwO2kOAMw44uyaaQMQO) and the [Developer Portal](https://developers.vtex.com/vtex-rest-api/docs/change-seller).
```

2023-06-15 19:41 UTC, julia-rabello commented on docs/guides/Checkout/configuration-section-api-quick-start-guides/get-and-update-the-seller-exchange-window.md
> +> ⚠️ The default window for changing a seller is **2 days**. However, you can change it for up to **30 days**.
```suggestion
> ⚠️ The default window for changing a seller is **2 days**. However, you can set the window for up to **30 days**.
```

2023-06-16 16:25 UTC, julia-rabello approved these changes

2023-06-16 17:07 UTC, merged