Fixing merchant journey api guides
vtexdocs/dev-portal-content pull request #55
Opened 2023-01-05 20:01 UTC by jumeyermattosarruda

This PR:
- Fixes broken image in Catalog quick start guide.
- Adds google forms to substitute the previous modal experience for measuring CSAT

2023-01-05 20:09 UTC, karenkrieger requested changes

2023-01-05 20:09 UTC, karenkrieger commented on docs/guides/Getting Started/catalog-overview.md
> +![VTEX Catalog architecture](https://raw.githubusercontent.com/vtexdocs/dev-portal-content/fixing-merchant-journey-API-guides/docs/guides/Getting%20Started/Catalog%20architecture.png)
Acho melhor não deixar a imagem com espaço, pode dar erro

2023-01-05 20:25 UTC, jumeyermattosarruda commented on docs/guides/Getting Started/catalog-overview.md
> +![VTEX Catalog architecture](https://raw.githubusercontent.com/vtexdocs/dev-portal-content/fixing-merchant-journey-API-guides/docs/guides/Getting%20Started/Catalog%20architecture.png)
Feito!

2023-01-06 14:50 UTC, karenkrieger approved these changes
LGTM

2023-01-06 17:03 UTC, merged