EDU-9705 add new JSON example
vtexdocs/dev-portal-content pull request #623
Opened 2023-08-04 16:14 UTC by geisecosta

#### Types of changes
- [x] New content (guides, endpoints, app documentation)
- [ ] Improvement (make a documentation even better)
- [ ] Fix (fix a documentation error)
- [ ] Spelling and grammar accuracy (self-explanatory)

2023-08-04 19:01 UTC, PedroAntunesCosta requested changes

2023-08-04 19:01 UTC, PedroAntunesCosta commented on docs/guides/Checkout/features/enable-the-region-for-skus.md
> +After updating the page where the SKUs are being viewed in the store, the price and availability information will be updated according to the region specified in the country and zip code information.
Esta sugestão tem o objetivo de [tirar a voz passiva](https://www.notion.so/vtexhandbook/Writing-guidelines-0351318ef29744d38398b318ca3da90d?pvs=4#d95dd84a951c42c9b48234e1361c251a) e tonar o texto mais direto. 

Além disso, não está claro para mim o que significa esse "updating". O conteúdo da página está sendo alterado no CMS? Ou se refere a atualizar a página no navegador? Se for esta segunda opção, acredito que o melhor verbo aqui seria "refreshing".

2023-08-04 19:04 UTC, PedroAntunesCosta commented
Além das sugestões que deixei acima, recomendo também fazer os ajustes de markdown indicados pelos bots.

2023-08-11 14:23 UTC, PedroAntunesCosta commented on docs/guides/Checkout/features/enable-the-region-for-skus.md
> +After updating the page where the SKUs are being viewed in the store, the price and availability information will be updated according to the region specified in the country and zip code information.
Alguma notícia sobre esse verbo?

2023-08-11 14:25 UTC, PedroAntunesCosta requested changes

2023-08-11 14:25 UTC, PedroAntunesCosta commented on docs/guides/Checkout/features/enable-the-region-for-skus.md
> +To verify that the session has updated the country and zip code data, send a `GET` request on the route below and search for the `country` and `Post Code` fields:
```suggestion
To verify that the session has updated the country and zip code data, send a `GET` request on the route below and search for the `country` and `postalCode` fields:
```

2023-08-14 11:58 UTC, geisecosta commented on docs/guides/Checkout/features/enable-the-region-for-skus.md
> +After updating the page where the SKUs are being viewed in the store, the price and availability information will be updated according to the region specified in the country and zip code information.
Olà, @PedroAntunesCosta 
Acredito que realmente o termo adequado seja o Refreshing, já fiz a atualização recomendada. Acredito que o termo adequado seja este, pois ao realizar a atualização via API, e o usuário tiver um produto no carrinho ele terá que fazer um refreshing da página, para que o produto seja atualizado, se não houver produtos no carrinho entendo que os preços e disponibilidades, já estarão corretos quando o produto for adicionado ao carrinho. No entento eu não consegui validar esta informação com o Rodolfo Bussola, pois ele se encontra de férias.
A quem vc me direcionaria para falar a respeito?

2023-08-14 14:00 UTC, PedroAntunesCosta commented on docs/guides/Checkout/features/enable-the-region-for-skus.md
> +After updating the page where the SKUs are being viewed in the store, the price and availability information will be updated according to the region specified in the country and zip code information.
Acho que vale consultar os experts do checkout. Vou te mandar no slack.

2023-08-22 18:39 UTC, PedroAntunesCosta approved these changes
LGTM

2023-08-22 18:43 UTC, merged