EDU-10006 add taxCode field
vtexdocs/dev-portal-content pull request #624
Opened 2023-08-07 12:55 UTC by geisecosta

#### Types of changes
- [x] New content (guides, endpoints, app documentation)
- [ ] Improvement (make a documentation even better)
- [ ] Fix (fix a documentation error)
- [ ] Spelling and grammar accuracy (self-explanatory)

2023-08-07 15:38 UTC, PedroAntunesCosta requested changes

2023-08-07 15:38 UTC, PedroAntunesCosta commented on docs/guides/Checkout/orderform-fields.md
> +|    taxCode |    String|  Tax code.    |
Cabe aqui descrever melhor o campo.

O que significa esse tax code? É um ID de uma taxa criada na VTEX? É um código relativo a impostos?

2023-08-14 11:37 UTC, geisecosta commented on docs/guides/Checkout/orderform-fields.md
> +|    taxCode |    String|  Tax code.    |
Olá, @PedroAntunesCosta!
Esclareci minhas dúvidas com Karen, e atualizei o documento, direcionando a PR para ela, conforme ela solicitou.

2023-08-14 19:08 UTC, karenkrieger approved these changes
LGTM

2023-08-16 17:35 UTC, karenkrieger approved these changes
LGTM

2023-08-16 19:32 UTC, PedroAntunesCosta approved these changes
LGTM

2023-08-16 19:33 UTC, merged