New: Documentation best practices guide
vtexdocs/dev-portal-content pull request #895
Opened 2024-01-04 14:10 UTC by Mariana-Caetano

#### Types of changes
- [x] New content (guides, endpoints, app documentation)
- [ ] Improvement (make a documentation even better)
- [ ] Fix (fix a documentation error)
- [ ] Spelling and grammar accuracy (self-explanatory)

2024-01-04 17:40 UTC, Mariana-Caetano commented on docs/vtex-io/Perks/vtex-io-documentation-homologation-requirements-for-vtex-app-store/vtex-io-documentation-guidelines.md
> +title: "Documentation best practices"
```suggestion
title: "Documentation guidelines"
```

2024-01-04 17:40 UTC, Mariana-Caetano commented on docs/vtex-io/Perks/vtex-io-documentation-homologation-requirements-for-vtex-app-store/vtex-io-documentation-engineering-guidelines.md
> +For more information on the best practices for creating documentation, refer to [Documentation Guideline](https://developers.vtex.com/docs/guides/vtex-io-documentation-documentation-guidelines)
```suggestion
For more information on the best practices for creating documentation, refer to [Documentation guidelines](https://developers.vtex.com/docs/guides/vtex-io-documentation-documentation-guidelines).
```

2024-01-04 17:45 UTC, Mariana-Caetano commented on navigation.json
> +              "name": "Documentation best practices",
```suggestion
              "name": "Documentation guidelines",
```

2024-01-04 17:53 UTC, Mariana-Caetano commented on docs/vtex-io/Perks/vtex-io-documentation-homologation-requirements-for-vtex-app-store/vtex-io-documentation-guidelines.md
> +#### Do’s
```suggestion
```

2024-01-04 20:00 UTC, Mariana-Caetano commented on docs/vtex-io/Perks/vtex-io-documentation-homologation-requirements-for-vtex-app-store/vtex-io-documentation-engineering-guidelines.md
> +For more information on the best practices for creating documentation, refer to [Documentation guidelines](https://developers.vtex.com/docs/guides/vtex-io-documentation-documentation-guidelines).
```suggestion
For more information on the best practices for creating documentation, refer to [Documentation guidelines](/).
```

2024-01-12 20:16 UTC, Mariana-Caetano commented on navigation.json
> +              "children": []
```suggestion
            }
```

2024-01-12 20:19 UTC, Mariana-Caetano commented on navigation.json
> +            }
```suggestion
```

2024-01-12 20:24 UTC, Mariana-Caetano commented on docs/vtex-io/Perks/vtex-io-documentation-homologation-requirements-for-vtex-app-store/vtex-io-documentation-docs-guidelines.md
> +3. {third step}.
```suggestion
1. *Describe the first step here*.
2. *Describe the second step here*.
3. *Describe the third step here*.
```

2024-01-15 13:44 UTC, Mariana-Caetano commented on docs/vtex-io/Perks/vtex-io-documentation-homologation-requirements-for-vtex-app-store/vtex-io-documentation-docs-guidelines.md
> +<br>
```suggestion
```

2024-01-15 13:59 UTC, carolinamenezes requested changes

2024-01-15 13:59 UTC, carolinamenezes commented on docs/vtex-io/Perks/vtex-io-documentation-homologation-requirements-for-vtex-app-store/vtex-io-documentation-docs-guidelines.md
> +❌Google Tag Manager v3.5.2.
```suggestion
| ✅ Do | ❌ Don't |
|-------|---------|
| Google Tag Manager | Google Tag Manager v3.5.2.|
| Live Shopping | Live Shopping app |
```
```

2024-01-15 13:59 UTC, carolinamenezes commented on docs/vtex-io/Perks/vtex-io-documentation-homologation-requirements-for-vtex-app-store/vtex-io-documentation-docs-guidelines.md
> +````bash
```suggestion
```bash
```

2024-01-15 13:59 UTC, carolinamenezes commented on docs/vtex-io/Perks/vtex-io-documentation-homologation-requirements-for-vtex-app-store/vtex-io-documentation-docs-guidelines.md
> +````
```suggestion
```
```

2024-01-15 13:59 UTC, carolinamenezes commented on docs/vtex-io/Perks/vtex-io-documentation-homologation-requirements-for-vtex-app-store/vtex-io-documentation-docs-guidelines.md
> +❌Google Tag Manager v3.5.2.
A visualização em tabela fica interessante para esses exemplos pq dá para ver lado a lado. Sugiro aplicar nos outros exemplos também

2024-01-15 13:59 UTC, carolinamenezes commented on docs/vtex-io/Perks/vtex-io-documentation-homologation-requirements-for-vtex-app-store/vtex-io-documentation-docs-guidelines.md
> +<summary><b>Documentation template</b></summary>
```suggestion
<summary>Documentation template</summary>
```

2024-01-15 13:59 UTC, carolinamenezes commented on docs/vtex-io/Perks/vtex-io-documentation-homologation-requirements-for-vtex-app-store/vtex-io-documentation-engineering-guidelines.md
> +For more information on the best practices for creating documentation, refer to [Documentation guidelines](/).
Ajustar link

2024-01-15 13:59 UTC, carolinamenezes commented on docs/vtex-io/Perks/vtex-io-documentation-homologation-requirements-for-vtex-app-store/vtex-io-documentation-docs-guidelines.md
> +    `![insert-an-image-preview](/)`
```suggestion
    ![insert-an-image-preview](/)
```

2024-01-15 17:46 UTC, carolinamenezes commented on docs/vtex-io/Perks/vtex-io-documentation-homologation-requirements-for-vtex-app-store/vtex-io-documentation-docs-guidelines.md
> +```bash
```suggestion
```markdown
```

2024-01-15 17:47 UTC, carolinamenezes approved these changes

2024-01-15 20:31 UTC, merged